### ISSUE TITLE
Incorrect 'aud' claim in access tokens

### ISSUE THREAD

**Issue by f74041153** [authlete/java-oauth-server#13]
The 'aud' claim in a access token  is meant to refer to the resource server.
However, my access token always has client_id in the 'aud' claim .
Is there something wrong?

**Comment by TakahikoKawasaki** [comment]
Access tokens issued by Authlete are just random strings (not JWTs) unless you use Authlete version 2.1+ and configure `Service.accessTokenSignAlg` properly. The version of Authlete running on `api.authlete.com` is 1.1, so if you are using `api.authlete.com`, JWTs you are seeing are not access tokens. Instead, they are ID tokens.

**Comment by f74041153** [comment]
I replaced API key/secret and token value in this command with mine ,then executing it. 
`curl -v -X POST https://api.authlete.com/api/auth/introspection/standard \
-H "Content-Type:application/json" \
-u '10167240235:LFpGEwpyHKNYMeMHg-H339X8gXdVlix-GoCHQAjAMaE' \
-d '{ "parameters":"token=VFGsNK-5sXiqterdaR7b5QbRX9VTwVCQB87jbr2_xAI&token_type_hint=access_token" }'`
The result I got after sending access token to the introspection endpoint has client_id in the 'aud' claim .

**Comment by TakahikoKawasaki** [comment]
@f74041153 Regarding the response from `/api/auth/introspection/standard`, we are sorry. It is a known issue in Authlete 1.1. It has already been fixed. If the bug in Authlete 1.1 (`api.authlete.com`) is critical for your project, I'll consider updating `api.authlete.com`.

**Comment by f74041153** [comment]
Thank you for updating `api.authlete.com`!
And how can I access the newer versions of Authlete ?

**Comment by TakahikoKawasaki** [comment]
@f74041153 Regarding newer versions of Authlete, please contact sales@authlete.com.

Authlete 2.1 is the latest version. It supports FAPI (Financial-grade API), CIBA (Client Initiated Backchannel Authentication), JARM (JWT Secured Authorization Response Mode for OAuth 2.0), JWT-based access tokens, etc.

One of remarkable points of the latest Authlete is that it is the world's first certified Financial-grade API (FAPI) OpenID Provider.

https://openid.net/certification/#FAPI_OPs

Please check the following articles if you are interested.

- [Financial-grade API (FAPI), explained by an implementer](https://medium.com/@darutk/financial-grade-api-fapi-explained-by-an-implementer-d09fcf2ff932)
- [“CIBA”, a new authentication/authorization technology in 2019, explained by an implementer](https://medium.com/@darutk/ciba-a-new-authentication-authorization-technology-in-2019-explained-by-an-implementer-d1e0ac1311b4)
